### ISSUE TITLE
Remove the markdown heading for this section

### ISSUE THREAD

**Issue by RonMallory** [DanteSellers/DanteSellers#1]
https://github.com/DanteSellers/DanteSellers/blob/0cade5a7e14b094129475f78b325519ba4b34bcc/README.md?plain=1#L11

Reference [markdown-cheatsheat]{https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet}

what you are trying to do here is to have raw html in the section that has the links.

If you want to keep raw markdown and not have any html, then download the images and store them in this repo, then render the images in markdown like ```![image-name](./path/to/image.png)``` with the root path being the directory of the readme.md.

**Comment by DanteSellers** [comment]
Rgr that. I continued to use the html file because using the markdown with svg seem to give me some issues.
